name: KiaiMC
version: ${version}
main: com.buape.kiaimc.KiaiMC
api: 1.21.8
author: thewilloftheshadow
depend: [DiscordSRV]
load: POSTWORLD
website: "https://github.com/buape/KiaiMC"
description: Synchronize your in-game messages and playtime with Kiai's XP
