name: KiaiMC
version: ${version}
main: com.buape.kiaimc.KiaiMC
api-version: 1.21.11
author: thewilloftheshadow
depend: [DiscordSRV, CommandAPI]
load: POSTWORLD
website: "https://github.com/buape/KiaiMC"
description: Synchronize your in-game messages and playtime with Kiai's XP
